language: python
python:
    - "2.6"
    - "2.7"
    - "3.3"
install:
    - pip install . --use-mirrors
    - pip install -r ci_requirements.txt --use-mirrors

script: nosetests --with-cov
after_success:
    - coveralls
