language: python
python:
    - "2.6"
    - "2.7"
    - "3.2"
install:
    - pip install . --use-mirrors
    - pip install -r test_requirements.txt --use-mirrors

script: python setup.py nosetests --with-cov
after_success:
    - coveralls
